### ISSUE TITLE
Workflow for checking the mod

### ISSUE THREAD

**Issue by LangLangBart** [0ad-matters/community-maps-2#105]
### Description
- [checkrefs.py](https://github.com/0ad/0ad/blob/master/source/tools/entity/checkrefs.py) is a good tool for testing the following:
  - check maps for missing actor and templates
  - verify actors files have no missing textures
  - check xml files match their (.rng) grammar file
- it would be beneficial if any kind of change to this mod would trigger the `checkrefs.py` script
  - best via a GitHub action workflow

#### Manual setup
- Currently, the user must verify the mod by first checking out 0 A.D. in the current release version.

```sh
# A26 current release tag
git restore --source A26 -SW < Path to 0 A.D. folder >
```

- navigate to the checkrefs script folder

```sh
cd < Path to 0 A.D. folder >/source/tools/entity
```

- run the script with the path to the `community-maps-2` mod and with the `-tax` option, see [readme.md](https://github.com/0ad/0ad/blob/master/source/tools/entity/readme.md) for explaination

```sh
python3 checkrefs.py -m < Path to community-maps-2 > -tax
INFO - Checking /Users/paria/Developer/community-maps-2's integrity.
# INFO - The following mods will be loaded: /Users/paria/Developer/community-maps-2|public|mod.
# INFO - Loading maps XML...
# INFO - Loading maps PMP...
# INFO - Loading entities...
# INFO - Loading actors...
# INFO - Loading variants...
# INFO - Loading art files...
# INFO - Loading materials...
# INFO - Loading particles...
# INFO - Loading sound groups...
# INFO - Loading audio files...
# INFO - Loading GUI XML...
# INFO - Loading GUI data...
# INFO - Loading civs...
# INFO - Loading random maps...
# INFO - Loading techs...
# INFO - Loading terrains...
# INFO - Loading auras...
# INFO - Loading tips...
# INFO - Looking for missing files...
# WARNING - Missing file 'art/actors/structures/hellenes/forge.xml' referenced by: /Users/paria/Developer/community-maps-2/maps/skirmishes/Lesvos Castle (2).xml
# WARNING - Missing file 'art/actors/structures/hellenes/sentry_tower.xml' referenced by: /Users/paria/Developer/community-maps-2/maps/skirmishes/Lesvos Castle (2).xml
# INFO - Validating actors...
...
```

---

#### Possible additional steps for Github actions
- check for typos, see #84

**Comment by andy5995** [comment]
>git restore --source A26 -SW < Path to 0 A.D. folder >

@LangLangBart i usually just use `git checkout A26` when I want to switch. But I see your point. ;)
