### ISSUE TITLE
Dune: OOS immediately after starting game

### ISSUE THREAD

**Issue by andy5995** [0ad-matters/community-maps-2#20]
I tried Dune with another player yesterday and we both got OOS immediately after the game started.

@nanihadesuka do you recall if there's anything on this map that could affect sync during network play?

**Comment by nanihadesuka** [comment]
Just checked the dune.js code and the dune generators, can't find anything suspicious. So no, no idea. I remember that I tried it long ago with multiple players and there was no OOS (in alpha 23). Without the diff can't do much anyway.

**Comment by andy5995** [comment]
Some messages in the client's terminal window:

```
ERROR: Failed to find matching prop point called "root" in model "art/meshes/gaia/dead_deciduous_3.dae" for actor "flora/trees/temperate_dead_forest.xml255"
TIMER| ParseEntities: 1.70052 s
TIMER| common/modern/setup.xml: 105.668 us
...
TIMER| session/styles.xml: 143.004 us
TIMER| session/session.xml: 134.882 ms
GAME STARTED, ALL INIT COMPLETE
Assertion failed: "numberOfVertices > 0"
Location: VertexBufferManager.cpp:128 (AllocateChunk)
```
