### ISSUE TITLE
Civ selection appears locked out in some cases

### ISSUE THREAD

**Issue by andy5995** [0ad-matters/community-maps-2#29]
There was some feedback on the [cm2 page of mod.io](https://0ad.mod.io/community-maps-2#230245)

>Hm, I don't quite get it. Trying to play Skirmish with these maps locked out the civs selection. Even if I had selected which ones I want to play with/against, they defaulted back to Athenians/Carthaginians.

>Edit: Oh apparently, the problem only appear if you go to the Browse Map option then hit Community Map filters and then choose the Skirmish maps from that bigger map screens. Go back to the Browse Map option and choose a map from other filter to break it out.

I haven't played around with that yet so I'm not sure if any changes can be made to this mod to prevent that kind of UI confusion...

**Comment by LangLangBart** [comment]
In the following gif, I selected some civs for a map, then selected the "Italian Peninsula (6)" and another map. The city selection is gone.
![gif](https://user-images.githubusercontent.com/92653266/222973018-602f709a-2b36-4569-873c-5ca42c554641.gif)

Some skirmish maps have the civ selection locked, if you remove the lock or move them to the scenario folder this issue should be resolved.
- `chess_2p` (scenario folder ?)
- `Italian Peninsula (6)` (remove the civ lock)

---

see [wiki/Mod_Layout#maps](https://trac.wildfiregames.com/wiki/Mod_Layout#maps)
> _Skirmishes are similar to scenarios, except the players' civilizations and teams can be chosen during game setup. Skirmishes are also created in Atlas._
