### ISSUE TITLE
Function call failed after selecting random map filter - 0.25.10

### ISSUE THREAD

**Issue by N0mi5** [0ad-matters/community-maps-2#30]
Installed latest version of community-maps 2: 0.25.10
After selecting the random map filter pyrogenisis throws following error:

Function call failed: return value was -120102 (Invalid/unsupported texture format)
Location: tex_dds.cpp:562 (decode_sd)

Call stack:

(0x555a5ffc0c26) pyrogenesis(+0x611c26) [0x555a5ffc0c26]
(0x555a5ff5fb50) pyrogenesis(+0x5b0b50) [0x555a5ff5fb50]
(0x555a5ff6168a) pyrogenesis(+0x5b268a) [0x555a5ff6168a]
(0x555a5ff5fd87) pyrogenesis(+0x5b0d87) [0x555a5ff5fd87]
(0x555a5ffe2c95) pyrogenesis(+0x633c95) [0x555a5ffe2c95]
(0x555a5ffe1994) pyrogenesis(+0x632994) [0x555a5ffe1994]
(0x555a5ffb53c1) pyrogenesis(+0x6063c1) [0x555a5ffb53c1]
(0x555a5ffb8013) pyrogenesis(+0x609013) [0x555a5ffb8013]
(0x555a5fdab44a) pyrogenesis(+0x3fc44a) [0x555a5fdab44a]
(0x555a5fdabc86) pyrogenesis(+0x3fcc86) [0x555a5fdabc86]
(0x555a5fda5978) pyrogenesis(+0x3f6978) [0x555a5fda5978]
(0x555a5ff4c4a1) pyrogenesis(+0x59d4a1) [0x555a5ff4c4a1]
(0x555a5fed5c70) pyrogenesis(+0x526c70) [0x555a5fed5c70]
(0x555a5ff33d74) pyrogenesis(+0x584d74) [0x555a5ff33d74]
(0x555a5fec34ef) pyrogenesis(+0x5144ef) [0x555a5fec34ef]
(0x555a5fc7f198) pyrogenesis(+0x2d0198) [0x555a5fc7f198]

errno = 11 (Try again later)
OS error = ?

tex_dds.cpp(562): Function call failed: return value was -120102 (Invalid/unsupported texture format)
zsh: segmentation fault (core dumped)  pyrogenesis community-maps-2-0.25.10.pyromod

**Comment by andy5995** [comment]
@N0mi5 Thanks for the report. Which OS are you using? And 0ad version?

I can't reproduce this on Manjaro, 0ad a25. Anyone else?

**Comment by N0mi5** [comment]
OS: Arch Linux
0ad: 25 build from 17.12.2021

**Comment by N0mi5** [comment]
Mod was downloaded from Github and installed via console (.pyromod file).
Unfortunately none of the above solutions did fix the problem.
Version 0.25.9 however is running absolutely smooth.

**Comment by andy5995** [comment]
Ok, I can reproduce this when I select the Povorotnaya random map. I'll do a fix and release today. Thanks @N0mi5

**Comment by StanleySweet** [comment]
Just for the record the Povorotnaya  had dimensions that are not a power of two, which might or might not be supported by GPUs. Happened with at least two 0 A.D. alphas, forcing a re-release.

**Comment by andy5995** [comment]
Thanks for the extra info @StanleySweet .

@na-Itms asked me to open a trac ticket for this, which I did. [6436](https://trac.wildfiregames.com/ticket/6436)

**Comment by StanleySweet** [comment]
Would you be so kind as to expand on what you would expect to happen when faced with such a bad texture?

**Comment by andy5995** [comment]
Ah.. no I don't think that would be a very efficient use of my time in this case. I'm sure the 0ad development team would be able to decide on the desired result, as you (and they) are much more familiar with how the program should behave.

**Comment by andy5995** [comment]
@StanleySweet Although I could participate in that discussion and possibly offer useful feedback.

**Comment by na-Itms** [comment]
> Would you be so kind as to expand on what you would expect to happen when faced with such a bad texture?

We should display an error message and we should not load the texture, but the engine shouldn't crash.
