### ISSUE TITLE
Don't fix civs in Skirmishes

### ISSUE THREAD

**Issue by xeruf** [0ad-matters/community-maps-2#46]
I experienced it in Italian Peninsula (6) now, but I think there are others too. I don't see why 0 AD even has the option to force civs,

**Comment by andy5995** [comment]
Hi @xeruf ,

By "fix" I think you mean civs should be changeable in the game setup by the players or the game admin.

I agree for the most part. I think some scenario makers have a vision in mind and it might sometimes mean that civs should be the same for a certain scenario, especially one that's based on a historical event.

So far I think I only changed that for one map, you see here on line 50 and 65

https://github.com/0ad-matters/community-maps-2/commit/2e4938f3cb52fa9ec0efecbc6798221372786f74#diff-67de04b2201defccb7e2f20879ec1e7b175e6e1d66c3f6f454be96b88d84c7b2

That will work, but if maps aren't using the default skirmish units, a player could select 'Britons' but instead start with an Athens civic center.

Note here on L2000

https://github.com/0ad-matters/community-maps-2/blob/2e4938f3cb52fa9ec0efecbc6798221372786f74/maps/skirmishes/The%20Duel%20(2).xml#L2000

When that happens, the game will still start with no errors, and the player will still produce Briton units.

That can happen with the other default starting units as well. They might start with a Athen's cav, Athen's pikemen, etc. In the Atlas editor, to make units match up with whatever civ was selected at game start, the map-maker needs to place default skirmish cav, infantry...

As 0ad is still in Alpha, I think the editor isn't quite finished yet. This stuff can all be done easily enough, but it's not always intuitive. I have had a problem before when making a map, making the civs selectable, but when I resave, the civs are reset back to fixed (in the .xml).

As for making the changes to the maps in this repository, I have no plans to do that right now. It's difficult enough to maintain my own maps, but to make a lot of time-consuming changes to other people's maps is not something I enjoy very much.

If anyone would like to correct a few maps, I'd accept a pull request for that though. Thank you for the feedback.

**Comment by andy5995** [comment]
There's a forum post with some related info https://wildfiregames.com/forum/topic/36649-upgrading-a23-skirmish-maps-to-be-compatible-with-a24/?do=findComment&comment=417669

**Comment by xeruf** [comment]
Yes, now that I think about it, it should be a feature of the game to change predefined civs.
But that "alpha" argument doesn't count, 0AD has been in alpha over a decade and it is an awesome game not worthy of that tag anymore, I guess by now the eternal alpha is kind of a tradition.
