### ISSUE TITLE
skirmishes/Lesvos Castle:missing entities

### ISSUE THREAD

**Issue by andy5995** [0ad-matters/community-maps-2#77]
ERROR: CCacheLoader failed to find archived or source file for: "art/actors/structures/hellenes/sentry_tower.xml"
ERROR: CObjectManager::FindActorDef(): Cannot find actor 'structures/hellenes/sentry_tower.xml'
ERROR: CCacheLoader failed to find archived or source file for: "art/actors/structures/hellenes/forge.xml"
ERROR: CObjectManager::FindActorDef(): Cannot find actor 'structures/hellenes/forge.xml'
ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/gaia/fruit/olive.xml"
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/gaia/fruit/olive.xml"
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/gaia/fruit/olive.xml"
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: Failed to load entity template 'gaia/fruit/olive'
ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/gaia/fruit/olive.xml"
ERROR: Failed to load entity template 'gaia/fruit/olive'

**Comment by LangLangBart** [comment]
- the olive is fixed with 9c2c47f66ee350b00ecc0f0de60a96a341ead2a8
- The rest of the issue came with  20e6dda474207fd8846b3acf1f249f839ae723dc
```diff
--- a/maps/skirmishes/Lesvos Castle (2).xml	
+++ b/maps/skirmishes/Lesvos Castle (2).xml	
@@ -176,13 +176,13 @@
 			<Actor seed="64210"/>
 		</Entity>
 		<Entity uid="28">
-			<Template>actor|structures/hellenes/sentry_tower.xml</Template>
+			<Template>actor|structures/hellenes/wooden_tower.xml</Template>
 			<Position x="255.96692" z="201.0127"/>
 			<Orientation y="3.14939"/>
 			<Actor seed="2202"/>
 		</Entity>
 		<Entity uid="29">
-			<Template>actor|structures/hellenes/sentry_tower.xml</Template>
+			<Template>actor|structures/hellenes/wooden_tower.xml</Template>
 			<Position x="254.84726" z="208.79627"/>
 			<Orientation y="-0.16704"/>
 			<Actor seed="56592"/>
@@ -284,7 +284,7 @@
 			<Actor seed="19480"/>
 		</Entity>
 		<Entity uid="48">
-			<Template>actor|structures/hellenes/forge.xml</Template>
+			<Template>actor|structures/hellenes/blacksmith.xml</Template>
 			<Position x="267.85975" z="224.284"/>
 			<Orientation y="-0.51041"/>
 			<Actor seed="35418"/>
```

---

Fixing it with
```sh
git show 20e6dda -- maps/skirmishes/Lesvos\ Castle\ \(2\).xml | git apply -R
```
